ignore:
  # Example: Ignore specific files or directories(Node.js only)_
  - "**/testing/**"
ignoreFlows:
  # Example: Ignore specific flows by their API names
  # - "Action_Call_In_A_Loop"
rules:
  FlowName:
    severity: error
    expression: "[A-Za-z0-9]+_[A-Za-z0-9]+"
  APIVersion:
    severity: warning
    expression: ">=50"