---
#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to master #
#######################################
name: "Build & Deploy - ALPHA"
on:
  push:
    branches:
      - "alpha"

permissions: read-all

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

###############
# Set the Job #
###############
jobs:
  deploy:
    name: Deploy alpha
    runs-on: ubuntu-latest
    permissions: read-all
    environment:
      name: alpha
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          always-auth: true
          # Defaults to the user or organization that owns the workflow file
          scope: "rubenhalman"
      - run: yarn
      - run: yarn config set version-git-tag false && tsc -b
      - run: ALPHAID=$(date '+%Y%m%d%H%M') && yarn version --prepatch --preid="alpha$ALPHAID"
      - run: yarn config set network-timeout 300000 && yarn publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
